var wjson = { Headline:
   { EffectiveDate: '2019-07-03T13:00:00+08:00',
     EffectiveEpochDate: 1562130000,
     Severity: 5,
     Text:
      'Air quality will be very unhealthy Thursday morning through Saturday afternoon',
     Category: 'rain',
     EndDate: '2019-07-03T19:00:00+08:00',
     EndEpochDate: 1562151600,
     MobileLink:
      'http://m.accuweather.com/en/cn/linchuan-township/94080/extended-weather-forecast/94080?unit=c&lang=en-us',
     Link:
      'http://www.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?unit=c&lang=en-us' },
  DailyForecasts:
   [ { Date: '2019-07-03T07:00:00+08:00',
       EpochDate: 1562108400,
       Sun: [Object],
       Moon: [Object],
       Temperature: [Object],
       RealFeelTemperature: [Object],
       RealFeelTemperatureShade: [Object],
       HoursOfSun: 1.1,
       DegreeDaySummary: [Object],
       AirAndPollen: [Array],
       Day: [Object],
       Night: [Object],
       Sources: [Array],
       MobileLink:
        'http://m.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=1&unit=c&lang=en-us',
       Link:
        'http://www.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=1&unit=c&lang=en-us' },
     { Date: '2019-07-04T07:00:00+08:00',
       EpochDate: 1562194800,
       Sun: [Object],
       Moon: [Object],
       Temperature: [Object],
       RealFeelTemperature: [Object],
       RealFeelTemperatureShade: [Object],
       HoursOfSun: 10.6,
       DegreeDaySummary: [Object],
       AirAndPollen: [Array],
       Day: [Object],
       Night: [Object],
       Sources: [Array],
       MobileLink:
        'http://m.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=2&unit=c&lang=en-us',
       Link:
        'http://www.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=2&unit=c&lang=en-us' },
     { Date: '2019-07-05T07:00:00+08:00',
       EpochDate: 1562281200,
       Sun: [Object],
       Moon: [Object],
       Temperature: [Object],
       RealFeelTemperature: [Object],
       RealFeelTemperatureShade: [Object],
       HoursOfSun: 10.3,
       DegreeDaySummary: [Object],
       AirAndPollen: [Array],
       Day: [Object],
       Night: [Object],
       Sources: [Array],
       MobileLink:
        'http://m.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=3&unit=c&lang=en-us',
       Link:
        'http://www.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=3&unit=c&lang=en-us' },
     { Date: '2019-07-06T07:00:00+08:00',
       EpochDate: 1562367600,
       Sun: [Object],
       Moon: [Object],
       Temperature: [Object],
       RealFeelTemperature: [Object],
       RealFeelTemperatureShade: [Object],
       HoursOfSun: 3.2,
       DegreeDaySummary: [Object],
       AirAndPollen: [Array],
       Day: [Object],
       Night: [Object],
       Sources: [Array],
       MobileLink:
        'http://m.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=4&unit=c&lang=en-us',
       Link:
        'http://www.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=4&unit=c&lang=en-us' },
     { Date: '2019-07-07T07:00:00+08:00',
       EpochDate: 1562454000,
       Sun: [Object],
       Moon: [Object],
       Temperature: [Object],
       RealFeelTemperature: [Object],
       RealFeelTemperatureShade: [Object],
       HoursOfSun: 8.7,
       DegreeDaySummary: [Object],
       AirAndPollen: [Array],
       Day: [Object],
       Night: [Object],
       Sources: [Array],
       MobileLink:
        'http://m.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=5&unit=c&lang=en-us',
       Link:
        'http://www.accuweather.com/en/cn/linchuan-township/94080/daily-weather-forecast/94080?day=5&unit=c&lang=en-us' } ] }